services:
  gpu_service:
    image: nvidia/cuda:12.9.0-base-ubuntu22.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ml_pipeline:
    image: kyghelani2/bert_lstm_news_classifier:latest
    # build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./src:/app/src
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
    depends_on:
      - gpu_service
