# Preprocessor Constants:

REQUIRED_COLUMS = ['headline', 'short_description', 'category']

MERGE_CATEGORIES_MAPPING = {
    'ARTS': 'ARTS_COMBINED',
    'ARTS & CULTURE': 'ARTS_COMBINED',
    'CULTURE & ARTS': 'ARTS_COMBINED',
    'PARENTING': 'PARENTING_COMBINED',
    'PARENTS': 'PARENTING_COMBINED',
    'WORLDPOST': 'WORLD_NEWS_COMBINED',
    'THE WORLDPOST': 'WORLD_NEWS_COMBINED',
    'WORLD NEWS': 'WORLD_NEWS_COMBINED',
    'FIFTY' : 'WORLD_NEWS_COMBINED',
    'U.S. NEWS' : 'WORLD_NEWS_COMBINED',
    'STYLE': 'STYLE_COMBINED',
    'STYLE & BEAUTY': 'STYLE_COMBINED',
    'WELLNESS': 'WELLNESS_COMBINED',
    'HEALTHY LIVING': 'WELLNESS_COMBINED',
    'GREEN': 'ENVIRONMENT_COMBINED',
    'ENVIRONMENT': 'ENVIRONMENT_COMBINED',
    'FOOD & DRINK': 'FOOD_COMBINED',
    'TASTE': 'FOOD_COMBINED',
    'EDUCATION' : 'EDUCATION_COMBINED',
    'COLLEGE': 'EDUCATION_COMBINED',
    'WEDDINGS': 'GOOD NEWS',
    'LATINO VOICES' : 'VOICES_COMBINED',
    'QUEER VOICES' : 'VOICES_COMBINED',
    'BLACK VOICES' : 'VOICES_COMBINED',
    'MONEY' : 'BUSINESS',
    'TECH' : 'SCI_TECH',
    'SCIENCE' : 'SCI_TECH'
}
